from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('employee_dashboard/', views.employee_dashboard, name='employee_dashboard'),
    path('signup/', views.signup_view, name='signup'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('home/', views.home, name='home'), 
    path('add-task', views.add_task, name='add_task'),
    path('add-employee/', views.add_employee, name='add_employee'),
    path('view-employees/', views.view_employees, name='view_employees'),
    path('update-employee/<int:id>/', views.update_employee, name='update_employee'),
    path('delete-employee/<int:employee_id>/', views.delete_employee, name='delete_employee'),
    # path('delete_task/<int:task_id>/', views.delete_task, name='delete_task'),
    path('task-stats/', views.task_stats, name='task-stats'),
    path('view-schedule/', views.view_schedule, name='view_schedule'),
    path('analytics', views.analytics, name='analytics'),
    path('edit-task/<int:task_id>/', views.edit_task, name='edit_task'),
    path('delete-task/<int:task_id>/', views.delete_task_view, name='delete_task'),
    path('api/schedule/', views.get_schedule_api, name='get-schedule-api'),
    path('api/task-analytics/', views.task_analytics, name='task_analytics'),
    path('task/<int:task_id>/update/', views.update_task_status, name='update_task_status'),
    path("update_task_status/<int:task_id>/", views.task_detail, name="update_task_status"),
    path('task/<int:task_id>/', views.task_detail, name='task_detail'),
    path('task/<int:task_id>/update_status/', views.update_task_status, name='update_task_status'),
    path('register_user/', views.register_user, name='register_user'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('logout_user', views.logout_user, name='logout_user'),
    path('get_notifications/', views.get_notifications, name='get_notifications'),
    path('about_us/', views.about_us, name='about_us'),
    path('download-pdf/', views.download_pdf, name='download_pdf'),
    path("our_employee/", views.our_employee, name="our_employee"),
    path('our_employee/<int:id>/', views.our_employee, name="our_employee"),
    path('Log_out/', views.Log_out, name='Log_out'),
    path("", views.employee_login, name="employee_login"),
    path("info/", views.employee_info, name="employee_info"),
    path("logout/", views.employee_logout, name="employee_logout"),
    path('chat/', views.chat_page, name='chat_page'),
    path("chat-api/", views.chat_api, name="chat_api"),
    path('settings/', views.settings_view, name='settings'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('delete-account/', views.delete_account, name='delete_account'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)