# Generated by Django 5.1.5 on 2025-01-22 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['reminder_time'], 'verbose_name': 'Reminder', 'verbose_name_plural': 'Reminders'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-deadline'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='reminder',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Reminder Completed'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_time',
            field=models.DateTimeField(verbose_name='Reminder Time'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.task', verbose_name='Associated Task'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Assigned User'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Task Duration (in hours)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Task Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, verbose_name='Priority Level'),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurring',
            field=models.BooleanField(default=False, verbose_name='Is Recurring Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10, verbose_name='Task Status'),
        ),
    ]
