# Generated by Django 5.1.5 on 2025-01-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
    ]
