# Generated by Django 5.1.5 on 2025-02-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbanker',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Subbanker', to='tasks.employee', verbose_name='Assigned Employee'),
        ),
    ]
