# Generated by Django 5.1.5 on 2025-02-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_subbanker_assigned_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/employees/'),
        ),
    ]
