# Generated by Django 5.1.5 on 2025-02-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
