# Generated by Django 5.1.5 on 2025-02-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_employee_options_remove_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
