# Generated by Django 5.1.5 on 2025-02-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_employee_image'),
    ]

    operations = [
    ]
