# Generated by Django 5.1.5 on 2025-02-16 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_employee_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='employees/default.png', upload_to='employees/'),
        ),
    ]
