# Generated by Django 5.1.5 on 2025-02-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_rename_created_at_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
