# Generated by Django 5.1.5 on 2025-02-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_task_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='default_password', max_length=255),
        ),
    ]
