# Generated by Django 5.1.5 on 2025-02-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_alter_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='task_pdfs/', verbose_name='Task PDF'),
        ),
    ]
