# Generated by Django 5.1.5 on 2025-02-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_task_depends_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='depends_on',
        ),
        migrations.AddField(
            model_name='task',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Notification Sent'),
        ),
    ]
