# Generated by Django 5.1.5 on 2025-02-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_remove_task_depends_on_task_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='notified',
        ),
    ]
